### ISSUE TITLE
New version for fedora 26 ?

### ISSUE THREAD

**Issue by bepolymathe** [abn/ghostwriter-rpm#1]
All in the title... do you think about a version of depo for fedora 26 ?
Tranks in advance !

**Comment by abn** [comment]
@bepolymathe sorry for not getting to this in any reasonable amount of time :( I have merged @Machiel 's work to support FC27 and have enabled FC26 too. Will validate builds work  before closing this out.

**Comment by abn** [comment]
Builds for v1.5.0-1.fc26 and fc27 are available now at https://copr.fedorainfracloud.org/coprs/abn/ghostwriter/
