### ISSUE TITLE
Release for Fedora 27? 

### ISSUE THREAD

**Issue by deejf** [abn/ghostwriter-rpm#2]
I had installed through this Copr on Fedora 25. Ever since, it's a no-go. Which is bad, as I make my living as a writer and editor, and Markdown is the way I write. It'd be nice to have my favorite editor without having to figure out how to compile the source with every new Fedora release.

**Comment by abn** [comment]
Thanks to @Machiel for creating #3.

@deejf newer builds should be available soon.

**Comment by abn** [comment]
Builds for v1.5.0-1.fc26 and fc27 are available now at https://copr.fedorainfracloud.org/coprs/abn/ghostwriter/
