### ISSUE TITLE
Version 1.6

### ISSUE THREAD

**Issue by orschiro** [abn/ghostwriter-rpm#4]
Hey @abn thanks so much for maintaining ghostwriter for Fedora!

You may have seen, version 1.6 is available [1].

Can you update your package in the Copr?

[1] https://github.com/wereturtle/ghostwriter/releases/tag/v1.6.0

**Comment by abn** [comment]
@orschiro not a problem.

**Comment by abn** [comment]
@orschiro the builds have been triggered at https://copr.fedorainfracloud.org/coprs/abn/ghostwriter/builds/

The rpms should be available once they are done.

**Comment by orschiro** [comment]
Thank you so much @abn ! :-)
